#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";

type DiagnosticSeverity = "error" | "warning";

type CliArgs = {
  workspace?: string;
  graph?: string;
  out?: string;
  allowGraphErrors: boolean;
  force: boolean;
};

type Diagnostic = {
  severity: DiagnosticSeverity;
  code: string;
  message: string;
  path: string;
};

type Boundary = {
  name: string | null;
  root: string;
  readme: string;
  contractScope: string;
};

type DependencyGraph = {
  schemaVersion?: string;
  workspace?: string;
  boundaries?: Boundary[];
  diagnostics?: Diagnostic[];
};

type Rule = {
  pattern: RulePattern;
  decision: "prompt" | "forbidden";
  justification: string;
  match: string[];
  notMatch?: string[];
};

type RulePattern = Array<string | string[]>;

const GENERATED_HEADER = `# Generated by contract-based-codex-permission-automation.
# Do not edit by hand; regenerate from the contract graph.
#
# Codex rules control which commands Codex may run outside the sandbox.
# They do not enforce filesystem boundary read/write permissions.
# Filesystem boundary isolation belongs in .codex/config.toml permission profiles.
# Project-local rules load only when the project .codex layer is trusted, and
# Codex must be restarted after rules change.
`;

const RULES: Rule[] = [
  {
    pattern: [["node", "node.exe"], ["-e", "--eval", "-p", "--print"]],
    decision: "forbidden",
    justification: "Inline Node execution outside the sandbox can read denied boundary files. Use a checked-in script under the active permission profile instead.",
    match: [
      "node -e \"require('fs').readFileSync('payment/index.ts', 'utf8')\"",
      "node --eval \"console.log(process.cwd())\"",
      "node -p \"process.env\"",
    ],
    notMatch: [
      "node scripts/scan-boundaries.mjs fixtures/basic-boundaries",
    ],
  },
  {
    pattern: [["python", "python.exe", "python3", "python3.exe", "py", "py.exe"], ["-c"]],
    decision: "forbidden",
    justification: "Inline Python execution outside the sandbox can bypass boundary filesystem permissions. Use a checked-in script under the active permission profile instead.",
    match: [
      "python -c \"open('payment/index.ts').read()\"",
      "python3 -c \"import os; print(os.environ)\"",
      "py -c \"print('inline')\"",
    ],
    notMatch: [
      "python scripts/tool.py",
    ],
  },
  {
    pattern: [["ruby", "ruby.exe", "perl", "perl.exe"], ["-e"]],
    decision: "forbidden",
    justification: "Inline interpreter execution outside the sandbox can bypass boundary filesystem permissions. Use a checked-in script under the active permission profile instead.",
    match: [
      "ruby -e \"puts File.read('payment/index.ts')\"",
      "perl -e \"print `type payment\\\\index.ts`\"",
    ],
    notMatch: [
      "ruby scripts/tool.rb",
      "perl scripts/tool.pl",
    ],
  },
  {
    pattern: [["php", "php.exe"], ["-r"]],
    decision: "forbidden",
    justification: "Inline PHP execution outside the sandbox can bypass boundary filesystem permissions. Use a checked-in script under the active permission profile instead.",
    match: [
      "php -r \"echo file_get_contents('payment/index.ts');\"",
    ],
    notMatch: [
      "php scripts/tool.php",
    ],
  },
  {
    pattern: [["rm", "rm.exe"], ["-rf", "-fr", "-r", "-R"]],
    decision: "forbidden",
    justification: "Recursive deletion outside the sandbox is too broad for boundary-isolated agent work. Ask a human to perform destructive cleanup deliberately.",
    match: [
      "rm -rf payment",
      "rm -r order",
    ],
    notMatch: [
      "rm README.md",
    ],
  },
  {
    pattern: [["rmdir", "rmdir.exe", "rd", "rd.exe"], ["/s", "/S"]],
    decision: "forbidden",
    justification: "Recursive deletion outside the sandbox is too broad for boundary-isolated agent work. Ask a human to perform destructive cleanup deliberately.",
    match: [
      "rmdir /s payment",
      "rd /S order",
    ],
    notMatch: [
      "rmdir empty-dir",
    ],
  },
  {
    pattern: [["bash", "bash.exe", "sh", "sh.exe", "zsh", "zsh.exe"], ["-c", "-lc"]],
    decision: "prompt",
    justification: "Shell wrappers can hide filesystem reads or writes. Approve only when the concrete command is understood and compatible with the active boundary profile.",
    match: [
      "bash -lc \"cat payment/index.ts\"",
      "sh -c \"npm test\"",
    ],
    notMatch: [
      "bash scripts/build.sh",
    ],
  },
  {
    pattern: [["powershell", "powershell.exe", "pwsh", "pwsh.exe"], ["-Command", "-command", "-EncodedCommand", "-encodedcommand", "-c", "-C"]],
    decision: "prompt",
    justification: "PowerShell command strings can hide filesystem reads or writes. Approve only when the concrete command is understood and compatible with the active boundary profile.",
    match: [
      "powershell -Command \"Get-Content payment/index.ts\"",
      "pwsh -EncodedCommand SQBFAFgA",
    ],
    notMatch: [
      "pwsh scripts/build.ps1",
    ],
  },
  {
    pattern: [["cmd", "cmd.exe"], ["/c", "/C"]],
    decision: "prompt",
    justification: "cmd command strings can hide filesystem reads or writes. Approve only when the concrete command is understood and compatible with the active boundary profile.",
    match: [
      "cmd /c type payment\\index.ts",
      "cmd /C npm test",
    ],
    notMatch: [
      "cmd scripts\\tool.cmd",
    ],
  },
  {
    pattern: [["npm", "npm.cmd", "pnpm", "pnpm.cmd"], ["install", "i", "ci", "add", "run", "exec", "dlx"]],
    decision: "prompt",
    justification: "Package manager commands can execute lifecycle scripts outside the sandbox. Approve only when dependency/script execution is intended.",
    match: [
      "npm install",
      "npm run build",
      "pnpm dlx tsx script.ts",
    ],
    notMatch: [
      "npm view some-package version",
    ],
  },
  {
    pattern: [["yarn", "yarn.cmd", "bun", "bun.exe"], ["install", "add", "run", "exec", "dlx", "x"]],
    decision: "prompt",
    justification: "Package manager commands can execute lifecycle scripts outside the sandbox. Approve only when dependency/script execution is intended.",
    match: [
      "yarn install",
      "yarn dlx tsx script.ts",
      "bun run build",
    ],
    notMatch: [
      "yarn info some-package version",
    ],
  },
  {
    pattern: [["npx", "npx.cmd", "bunx", "bunx.exe"]],
    decision: "prompt",
    justification: "One-shot package executors can download or run arbitrary code outside the sandbox. Approve only when the executable and source are trusted.",
    match: [
      "npx tsx script.ts",
      "bunx vite",
    ],
    notMatch: [],
  },
  {
    pattern: [["git", "git.exe"], ["commit", "merge", "rebase", "reset", "clean", "apply", "am"]],
    decision: "prompt",
    justification: "State-changing git commands outside the sandbox can modify the workspace or run hooks. Approve only when the operation is intentional.",
    match: [
      "git commit -m change",
      "git reset --hard",
      "git clean -fd",
    ],
    notMatch: [
      "git status",
      "git diff",
    ],
  },
  {
    pattern: [["codex", "codex.exe"]],
    decision: "prompt",
    justification: "Nested Codex runs may use a different permission posture. Approve only when the nested session's permissions are explicitly intended.",
    match: [
      "codex exec \"read payment/index.ts\"",
    ],
    notMatch: [],
  },
];

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const workspace = path.resolve(args.workspace ?? process.cwd());
  const graphPath = path.resolve(process.cwd(), args.graph ?? path.join(workspace, ".codex", "dependency-graph.json"));
  const graph = await readGraph(graphPath);
  const diagnostics = validateGraph(graph);

  if (!args.allowGraphErrors && diagnostics.some((diagnostic) => diagnostic.severity === "error")) {
    for (const diagnostic of diagnostics) {
      process.stderr.write(formatDiagnostic(diagnostic));
    }
    process.exitCode = 1;
    return;
  }

  for (const diagnostic of diagnostics.filter((item) => item.severity === "warning")) {
    process.stderr.write(formatDiagnostic(diagnostic));
  }

  const rules = renderRules(graph, {
    graphPath: toDisplayPath(workspace, graphPath),
  });

  if (args.out) {
    const outPath = path.resolve(process.cwd(), args.out);
    if (!args.force && await fileExists(outPath)) {
      throw new Error(`Refusing to overwrite existing file without --force: ${outPath}`);
    }
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, `${rules}\n`, "utf8");
  } else {
    process.stdout.write(`${rules}\n`);
  }
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    workspace: undefined,
    graph: undefined,
    out: undefined,
    allowGraphErrors: false,
    force: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--graph") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--graph requires a file path.");
      }
      args.graph = value;
      index += 1;
      continue;
    }

    if (arg === "--out") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--out requires a file path.");
      }
      args.out = value;
      index += 1;
      continue;
    }

    if (arg === "--allow-graph-errors") {
      args.allowGraphErrors = true;
      continue;
    }

    if (arg === "--force") {
      args.force = true;
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }

    if (arg.startsWith("--")) {
      throw new Error(`Unknown option: ${arg}`);
    }

    if (args.workspace) {
      throw new Error(`Unexpected positional argument: ${arg}`);
    }

    args.workspace = arg;
  }

  return args;
}

function printHelp(): void {
  process.stdout.write(`Usage: node src/generate-codex-rules.ts [workspace] [--graph path] [--out path]

Generates Codex .rules policy for command escalation guardrails.

Options:
  --graph <path>          Contract graph JSON. Defaults to <workspace>/.codex/dependency-graph.json.
  --out <path>            Write .rules file instead of stdout.
  --allow-graph-errors    Generate even when graph diagnostics contain errors.
  --force                 Allow --out to overwrite an existing file.
  -h, --help              Show this help.
`);
}

async function readGraph(graphPath: string): Promise<DependencyGraph> {
  const content = await fs.readFile(graphPath, "utf8");
  return JSON.parse(content) as DependencyGraph;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function validateGraph(graph: DependencyGraph): Diagnostic[] {
  const diagnostics: Diagnostic[] = [...(graph.diagnostics ?? [])];
  const names = new Set<string>();

  if (!Array.isArray(graph.boundaries) || graph.boundaries.length === 0) {
    diagnostics.push({
      severity: "error",
      code: "no_boundaries",
      message: "Contract graph does not contain any boundaries.",
      path: ".",
    });
  }

  for (const boundary of graph.boundaries ?? []) {
    if (!boundary.name) {
      diagnostics.push({
        severity: "error",
        code: "boundary_name_missing",
        message: "Boundary is missing a name.",
        path: boundary.readme ?? ".",
      });
      continue;
    }

    if (names.has(boundary.name)) {
      diagnostics.push({
        severity: "error",
        code: "duplicate_boundary_name",
        message: `Boundary name '${boundary.name}' is declared more than once.`,
        path: boundary.readme,
      });
    }
    names.add(boundary.name);
  }

  return diagnostics;
}

function renderRules(graph: DependencyGraph, options: { graphPath: string }): string {
  const lines: string[] = [
    GENERATED_HEADER.trimEnd(),
    "",
    `# Source contract graph: ${options.graphPath}`,
    ...renderBoundaryComments(graph),
    "",
  ];

  for (const rule of RULES) {
    lines.push(renderRule(rule));
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

function renderBoundaryComments(graph: DependencyGraph): string[] {
  const boundaries = [...(graph.boundaries ?? [])]
    .map((boundary) => boundary.name)
    .filter((name): name is string => Boolean(name))
    .sort((left, right) => left.localeCompare(right));

  if (boundaries.length === 0) {
    return [];
  }

  return [
    "# Boundaries in source graph:",
    ...boundaries.map((boundary) => `# - ${sanitizeComment(boundary)}`),
  ];
}

function renderRule(rule: Rule): string {
  const lines = [
    "prefix_rule(",
    `    pattern = ${renderStarlarkValue(rule.pattern)},`,
    `    decision = ${renderStarlarkValue(rule.decision)},`,
    `    justification = ${renderStarlarkValue(rule.justification)},`,
    `    match = ${renderStarlarkValue(rule.match)},`,
    `    not_match = ${renderStarlarkValue(rule.notMatch ?? [])},`,
    ")",
  ];

  return lines.join("\n");
}

function renderStarlarkValue(value: string | string[] | RulePattern): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  return `[${value.map((item) => renderStarlarkValue(item)).join(", ")}]`;
}

function sanitizeComment(value: string): string {
  return value.replace(/[\r\n]/g, " ").trim();
}

function toDisplayPath(workspace: string, target: string): string {
  const relative = path.relative(workspace, target);
  return relative ? normalizePath(relative) : ".";
}

function normalizePath(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function formatDiagnostic(diagnostic: Diagnostic): string {
  return `[${diagnostic.severity}] ${diagnostic.code}: ${diagnostic.message} (${diagnostic.path})\n`;
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
