#!/usr/bin/env node

import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";

type DiagnosticSeverity = "error" | "warning";
type CliArgs = {
  workspace?: string;
  graph?: string;
  out?: string;
  defaultBoundary?: string;
  allowGraphErrors: boolean;
  allowRootBoundary: boolean;
  force: boolean;
};

type Diagnostic = {
  severity: DiagnosticSeverity;
  code: string;
  message: string;
  path: string;
};

type Boundary = {
  name: string | null;
  root: string;
  readme: string;
  contractFiles?: string[];
  publicArtifacts?: string[];
  dependencies?: string[];
  contractScope: string;
  metadata?: Record<string, unknown>;
};

type DependencyGraph = {
  schemaVersion?: string;
  workspace?: string;
  boundaries: Boundary[];
  diagnostics?: Diagnostic[];
};

type Profile = {
  name: string;
  boundary: Boundary;
  dependencies: Boundary[];
  entries: Map<string, "read" | "write" | "deny">;
};

const GENERATED_HEADER = `# Generated by contract-based-codex-permission-automation.
# Do not edit by hand; regenerate from the contract graph.
#
# Security boundary:
# - These profiles constrain Codex agents only when Codex permission profiles are enforced.
# - They do not constrain human developers.
# - Do not run boundary-isolated agents with :danger-full-access or sandbox_mode = "danger-full-access".
# - Project lint rules remain responsible for public entrypoint/deep import policy.
`;

const SENSITIVE_DENY_GLOBS = [
  "**/*.env",
  "**/.env.*",
  "**/*secret*",
  "**/*token*",
  "**/*credential*",
];

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const workspace = path.resolve(args.workspace ?? process.cwd());
  const graphPath = path.resolve(process.cwd(), args.graph ?? path.join(workspace, ".codex", "dependency-graph.json"));
  const graph = await readGraph(graphPath);
  const diagnostics = validateGraph(graph, args);

  if (!args.allowGraphErrors && diagnostics.some((diagnostic) => diagnostic.severity === "error")) {
    for (const diagnostic of diagnostics) {
      process.stderr.write(formatDiagnostic(diagnostic));
    }
    process.exitCode = 1;
    return;
  }

  for (const diagnostic of diagnostics.filter((item) => item.severity === "warning")) {
    process.stderr.write(formatDiagnostic(diagnostic));
  }

  const profiles = buildProfiles(graph);
  const defaultProfile = resolveDefaultProfile(args.defaultBoundary, profiles);
  const toml = renderConfigToml(profiles, {
    graphPath: toDisplayPath(workspace, graphPath),
    defaultProfile,
  });

  if (args.out) {
    const outPath = path.resolve(process.cwd(), args.out);
    if (!args.force && await fileExists(outPath)) {
      throw new Error(`Refusing to overwrite existing file without --force: ${outPath}`);
    }
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, `${toml}\n`, "utf8");
  } else {
    process.stdout.write(`${toml}\n`);
  }
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    workspace: undefined,
    graph: undefined,
    out: undefined,
    defaultBoundary: undefined,
    allowGraphErrors: false,
    allowRootBoundary: false,
    force: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--graph") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--graph requires a file path.");
      }
      args.graph = value;
      index += 1;
      continue;
    }

    if (arg === "--out") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--out requires a file path.");
      }
      args.out = value;
      index += 1;
      continue;
    }

    if (arg === "--default-boundary") {
      const value = argv[index + 1];
      if (!value) {
        throw new Error("--default-boundary requires a boundary name.");
      }
      args.defaultBoundary = value;
      index += 1;
      continue;
    }

    if (arg === "--allow-graph-errors") {
      args.allowGraphErrors = true;
      continue;
    }

    if (arg === "--allow-root-boundary") {
      args.allowRootBoundary = true;
      continue;
    }

    if (arg === "--force") {
      args.force = true;
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }

    if (arg.startsWith("--")) {
      throw new Error(`Unknown option: ${arg}`);
    }

    if (args.workspace) {
      throw new Error(`Unexpected positional argument: ${arg}`);
    }

    args.workspace = arg;
  }

  return args;
}

function printHelp(): void {
  process.stdout.write(`Usage: node src/generate-codex-permissions.ts [workspace] [--graph path] [--out path]

Generates Codex permission profiles from Markdown-declared contract boundary JSON.

Options:
  --graph <path>              Contract graph JSON. Defaults to <workspace>/.codex/dependency-graph.json.
  --out <path>                Write config TOML to a file instead of stdout.
  --default-boundary <name>   Emit default_permissions for the matching boundary profile.
  --allow-graph-errors        Generate even when graph diagnostics contain errors.
  --allow-root-boundary       Allow a boundary whose root is ".".
  --force                     Allow --out to overwrite an existing file.
  -h, --help                  Show this help.
`);
}

async function readGraph(graphPath: string): Promise<DependencyGraph> {
  const content = await fs.readFile(graphPath, "utf8");
  return JSON.parse(content) as DependencyGraph;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function validateGraph(graph: DependencyGraph, args: CliArgs): Diagnostic[] {
  const diagnostics: Diagnostic[] = [...(graph.diagnostics ?? [])];
  const names = new Set<string>();

  if (!Array.isArray(graph.boundaries) || graph.boundaries.length === 0) {
    diagnostics.push({
      severity: "error",
      code: "no_boundaries",
      message: "Contract graph does not contain any boundaries.",
      path: ".",
    });
  }



  for (const boundary of graph.boundaries ?? []) {
    if (!boundary.name) {
      diagnostics.push({
        severity: "error",
        code: "boundary_name_missing",
        message: "Boundary is missing a name.",
        path: boundary.readme ?? ".",
      });
      continue;
    }

    if (names.has(boundary.name)) {
      diagnostics.push({
        severity: "error",
        code: "duplicate_boundary_name",
        message: `Boundary name '${boundary.name}' is declared more than once.`,
        path: boundary.readme,
      });
    }
    names.add(boundary.name);

    if (!isSafeWorkspaceRelativePath(boundary.root) || !isSafeWorkspaceRelativePath(boundary.readme)) {
      diagnostics.push({
        severity: "error",
        code: "unsafe_boundary_path",
        message: "Boundary root/readme must be workspace-relative paths without parent traversal.",
        path: boundary.readme ?? ".",
      });
    }

    if (boundary.root === "." && !args.allowRootBoundary) {
      diagnostics.push({
        severity: "error",
        code: "root_boundary_not_allowed",
        message: "Root boundary would grant write access to the whole workspace. Pass --allow-root-boundary only when this is intentional.",
        path: boundary.readme,
      });
    }

    if (!isSameOrChildPath(boundary.root, boundary.readme)) {
      diagnostics.push({
        severity: "error",
        code: "boundary_readme_outside_root",
        message: "Boundary entrypoint document must be inside its boundary root.",
        path: boundary.readme,
      });
    }

    if (Array.isArray(boundary.contractFiles)) {
      const contractFiles = boundary.contractFiles;
      if (!contractFiles.includes(boundary.readme)) {
        diagnostics.push({
          severity: "error",
          code: "boundary_readme_missing_from_contract_files",
          message: "Boundary contractFiles must include the boundary entrypoint document.",
          path: boundary.readme,
        });
      }

      for (const contractFile of contractFiles) {
        if (!isSafeWorkspaceRelativePath(contractFile) || !isSameOrChildPath(boundary.root, contractFile)) {
          diagnostics.push({
            severity: "error",
            code: "contract_file_outside_boundary",
            message: "Boundary contractFiles must stay inside the boundary root.",
            path: contractFile,
          });
        }
      }
    }

    for (const publicArtifact of publicArtifactsForBoundary(boundary)) {
      if (!isSafeWorkspaceRelativePath(publicArtifact) || !isSameOrChildPath(boundary.root, publicArtifact)) {
        diagnostics.push({
          severity: "error",
          code: "public_artifact_outside_boundary",
          message: "Boundary publicArtifacts must stay inside the boundary root.",
          path: publicArtifact,
        });
      }
    }
  }

  for (const boundary of graph.boundaries ?? []) {
    if (!boundary.name || !Array.isArray(boundary.dependencies)) {
      continue;
    }

    for (const dependencyName of dependencyNamesForBoundary(boundary)) {
      if (!names.has(dependencyName)) {
        diagnostics.push({
          severity: "error",
          code: "unknown_declared_dependency",
          message: `Boundary '${boundary.name}' declares unknown contract dependency '${dependencyName}'.`,
          path: boundary.readme ?? ".",
        });
      }
    }
  }

  return diagnostics;
}

function buildProfiles(graph: DependencyGraph): Profile[] {
  const boundaries = [...graph.boundaries].sort((left, right) => safeName(left).localeCompare(safeName(right)));
  const byName = new Map(boundaries.map((boundary) => [safeName(boundary), boundary]));
  const usedProfileNames = new Map<string, number>();

  return boundaries.map((boundary) => {
    const boundaryName = safeName(boundary);
    const profileName = uniqueProfileName(`agent-${slugify(boundaryName)}`, usedProfileNames);
    const dependencies = dependencyNamesForBoundary(boundary)
      .map((name) => byName.get(name))
      .filter((item): item is Boundary => Boolean(item))
      .sort((left, right) => safeName(left).localeCompare(safeName(right)));
    const entries = buildFilesystemEntries(boundary, boundaries, dependencies);

    return {
      name: profileName,
      boundary,
      dependencies,
      entries,
    };
  });
}

function buildFilesystemEntries(owner: Boundary, boundaries: Boundary[], dependencies: Boundary[]): Map<string, "read" | "write" | "deny"> {
  const entries = new Map<string, "read" | "write" | "deny">();

  entries.set(".", "read");
  entries.set(".codex", "read");

  for (const boundary of boundaries) {
    if (safeName(boundary) !== safeName(owner)) {
      entries.set(boundary.root, "deny");
    }
  }

  entries.set(owner.root, "write");

  for (const dependency of dependencies) {
    for (const readableFile of readableFilesForBoundary(dependency)) {
      entries.set(readableFile, "read");
    }
  }

  for (const pattern of SENSITIVE_DENY_GLOBS) {
    entries.set(pattern, "deny");
  }

  return entries;
}

function renderConfigToml(profiles: Profile[], options: { graphPath: string; defaultProfile: string | null }): string {
  const lines: string[] = [GENERATED_HEADER.trimEnd(), "", `# Source contract graph: ${options.graphPath}`];

  if (options.defaultProfile) {
    lines.push(`default_permissions = ${tomlString(options.defaultProfile)}`, "");
  } else {
    lines.push("# No default_permissions emitted. Select a generated profile explicitly for a boundary agent.", "");
  }

  for (const profile of profiles) {
    const boundaryName = safeName(profile.boundary);
    const dependencyList = profile.dependencies.map((dependency) => safeName(dependency)).join(", ") || "none";

    lines.push(`[permissions.${profile.name}]`);
    lines.push(`description = ${tomlString(`${boundaryName} boundary agent. Owns ${profile.boundary.root}; direct dependency public surfaces: ${dependencyList}.`)}`);
    lines.push("");
    lines.push(`[permissions.${profile.name}.filesystem]`);
    lines.push(`":minimal" = "read"`);
    lines.push("glob_scan_max_depth = 4");
    lines.push("");
    lines.push(`[permissions.${profile.name}.filesystem.":workspace_roots"]`);

    for (const [entryPath, access] of sortFilesystemEntries(profile.entries)) {
      lines.push(`${tomlString(entryPath)} = ${tomlString(access)}`);
    }

    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

function sortFilesystemEntries(entries: Map<string, "read" | "write" | "deny">): [string, "read" | "write" | "deny"][] {
  const rank = new Map([
    [".", 0],
    [".codex", 1],
  ]);

  return [...entries.entries()].sort(([leftPath], [rightPath]) => {
    const leftRank = rank.get(leftPath) ?? (leftPath.includes("*") ? 4 : 2);
    const rightRank = rank.get(rightPath) ?? (rightPath.includes("*") ? 4 : 2);

    if (leftRank !== rightRank) {
      return leftRank - rightRank;
    }

    return leftPath.localeCompare(rightPath);
  });
}

function contractFilesForBoundary(boundary: Boundary): string[] {
  const files = Array.isArray(boundary.contractFiles) && boundary.contractFiles.length > 0
    ? boundary.contractFiles
    : [boundary.readme];
  return [...new Set(files)];
}

function publicArtifactsForBoundary(boundary: Boundary): string[] {
  return Array.isArray(boundary.publicArtifacts) ? [...new Set(boundary.publicArtifacts)] : [];
}

function readableFilesForBoundary(boundary: Boundary): string[] {
  return [...new Set([...contractFilesForBoundary(boundary), ...publicArtifactsForBoundary(boundary)])];
}

function dependencyNamesForBoundary(boundary: Boundary): string[] {
  return [...new Set((boundary.dependencies ?? []).filter((name): name is string => typeof name === "string" && name.length > 0))];
}

function resolveDefaultProfile(defaultBoundary: string | undefined, profiles: Profile[]): string | null {
  if (!defaultBoundary) {
    return null;
  }

  const match = profiles.find((profile) => safeName(profile.boundary) === defaultBoundary);
  if (!match) {
    throw new Error(`--default-boundary '${defaultBoundary}' does not match a generated boundary.`);
  }

  return match.name;
}

function safeName(boundary: Boundary): string {
  if (!boundary.name) {
    throw new Error(`Boundary at ${boundary.readme} is missing a name.`);
  }

  return boundary.name;
}

function uniqueProfileName(baseName: string, used: Map<string, number>): string {
  const count = used.get(baseName) ?? 0;
  used.set(baseName, count + 1);

  if (count === 0) {
    return baseName;
  }

  return `${baseName}-${count + 1}`;
}

function slugify(value: string): string {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "boundary";
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function isSafeWorkspaceRelativePath(value: string | undefined): boolean {
  if (!value) {
    return false;
  }

  if (value === ".") {
    return true;
  }

  const normalized = normalizePath(value);
  return !path.isAbsolute(value) && !normalized.startsWith("../") && !normalized.includes("/../") && normalized !== "..";
}

function isSameOrChildPath(parent: string, child: string): boolean {
  const relative = path.posix.relative(normalizePath(parent), normalizePath(child));
  return relative === "" || (!relative.startsWith("..") && !path.posix.isAbsolute(relative));
}

function toDisplayPath(workspace: string, target: string): string {
  const relative = path.relative(workspace, target);
  return relative ? normalizePath(relative) : ".";
}

function normalizePath(value: string): string {
  return value.replaceAll(path.sep, "/");
}

function formatDiagnostic(diagnostic: Diagnostic): string {
  return `[${diagnostic.severity}] ${diagnostic.code}: ${diagnostic.message} (${diagnostic.path})\n`;
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
